name: Run the tests

on:
   push:
       branches: [ main ]
   pull_request:
       branches: [ main ]
   workflow_dispatch:

   jobs:
     test:
       runs-on: ubuntu-latest

    steps:
       - name: Check out project
         use:  actions/checlout@v2

       _ name: Istall Node.js
         use:  actions/setup-node@v3
         with:
             node-version: '18'

       - name: Clean istall the project
         run: npm ci

       - name: Install Playwright
         run: npx playwright install --with-deps

       - name: run Playwright tests
         run:  npx playwright test 

       - uses: actions/upload-artifact@v3
         if: always() 
          with: 
            name: playwright-report  
            path: playwright-report/
            retention-days: 30 
                   




